services:
  # 백엔드 서비스
  - type: web
    name: coffee-order-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-order-db
          property: connectionString

  # 프론트엔드 서비스  
  - type: web
    name: coffee-order-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://coffee-order-backend.onrender.com/api

databases:
  - name: coffee-order-db
    plan: free
